default:
  server:
    port: 3333
  website:
    title: '搜狗Mocker server'
  wwwroot: 'data'
  reservedWords: ''
  logger:
    level:
      development: 'DEBUG'
      production: 'ERROR'

  mocker_server_host: 'mockserver.sogou-inc.com'
  mocker_server_prefix: 'mockrest'
  mocker_project_id: -1













